// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tokenizer = require("./tokenizer.bs.js");

Tokenizer.tokenize("(add 2 (sub 4))");

console.log("tiny compiler in rescript");

/*  Not a pure module */
