// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tokenizer = require("./tokenizer.bs.js");

Tokenizer.tokenize("(cool + 2) NICE");

console.log("tiny compiler in rescript");

/*  Not a pure module */
