// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");

function tokenizeStrings(input) {
  var current = 0;
  var tokens = [];
  var stringArray = input.split("");
  while(current < input.length) {
    var c = Caml_array.get(stringArray, current);
    var value = c;
    var isOpenParen = /\(/.test(c);
    var isCloseParen = /\)/.test(c);
    var isNumber = /^[0-9]/.test(c);
    var isWhitespace = /\s/.test(c);
    if (isOpenParen) {
      current = current + 1 | 0;
      tokens.push(/* ParenOpen */0);
      console.log(/* ParenOpen */0);
    } else if (isCloseParen) {
      current = current + 1 | 0;
      tokens.push(/* ParenClose */1);
      console.log(/* ParenOpen */0);
    } else if (isNumber) {
      var isNextMatch = /^[0-9]/.test(value);
      while(isNextMatch && current < input.length) {
        current = current + 1 | 0;
        console.log(value);
      };
    } else {
      current = current + 1 | 0;
      if (!isWhitespace) {
        tokens.push({
              TAG: /* NoOpt */0,
              _0: 0
            });
        console.log({
              TAG: /* NoOpt */0,
              _0: 222
            });
      }
      
    }
  };
  
}

tokenizeStrings("hello nerds 12345 ( )");

exports.tokenizeStrings = tokenizeStrings;
/*  Not a pure module */
