// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");

function tokenize(input) {
  new RegExp("/\\s/");
  var numRegex = new RegExp("/[0-9]/");
  var lettersRegex = new RegExp("/[a-z]/");
  var current = {
    contents: 0
  };
  var $$break = {
    contents: false
  };
  var chars = input.split("");
  var tokens = chars.map(function ($$char) {
        numRegex.test($$char);
        lettersRegex.test($$char);
        var neArr = [];
        switch ($$char) {
          case " " :
              return {
                      name: "space",
                      value: $$char
                    };
          case "(" :
          case ")" :
              current.contents = current.contents + 1 | 0;
              return {
                      name: "paren",
                      value: $$char
                    };
          default:
            var maxLen = chars.length - 1 | 0;
            while($$break.contents === false && current.contents < maxLen) {
              var currentChar = Caml_array.get(chars, current.contents);
              if (currentChar === " ") {
                $$break.contents = true;
              } else {
                console.log(currentChar);
                neArr.push(currentChar);
                console.log("curr: ", neArr);
                current.contents = current.contents + 1 | 0;
              }
            };
            var combinedValue = neArr.join("");
            return {
                    name: "letter",
                    value: combinedValue
                  };
        }
      });
  console.log(tokens);
  
}

exports.tokenize = tokenize;
/* No side effect */
